### POST create user
# it's created and returned access and refresh tokens
#  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYXZsQGdtYWlsLmNvbSIsImlhdCI6MTcxNTc3NDI5OCwiZXhwIjoxNzE1Nzc1NzM4fQ.bU0pzXWRiM2Ziq7cfAmxdKx62_zN92pZNFD-WoUA2Zg",
#  "refreshToken": "c5fb851c-597f-43b2-afb5-8bd9adb59196"
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name" : "marat",
    "email" : "davl@gmail.com",
    "username" : "nexoc",
    "password" : "12345"
}


### POST create user
# it is returned access and refresh tokens
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name" : "admin",
  "email" : "admin@gmail.com",
  "username" : "admin",
  "password" : "12345"
}


### POST login with email and password
# it's returned new access token
#  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYXZsQGdtYWlsLmNvbSIsImlhdCI6MTcxNTc3NDM0OCwiZXhwIjoxNzE1Nzc1Nzg4fQ.5vzANA8SU_WDq7ryOoYeKILp2mUM08AdyoL3Rz7Ysrs",
#  "refreshToken": "c5fb851c-597f-43b2-afb5-8bd9adb59196"
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email" : "davl@gmail.com",
  "password" : "12345"
}


### POST refresh access token with refresh token
# access token has been refreshed, we got new one
#  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYXZsQGdtYWlsLmNvbSIsImlhdCI6MTcxNTc3NDU5MSwiZXhwIjoxNzE1Nzc2MDMxfQ.tUw7RLk2xH3uuD2KAGwrAYu3l1IWAdexhb2by_gGbCw",
#  "refreshToken": "c5fb851c-597f-43b2-afb5-8bd9adb59196"
POST localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken" : "7f50cd9f-8626-41f4-a445-ec5c2e28d645"
}


